// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: imageprocessor.proto
// Protobuf C++ Version: 5.29.3

#include "imageprocessor.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace imageprocessor {

inline constexpr ImageRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : image_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        operation_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ImageRequest::ImageRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ImageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageRequestDefaultTypeInternal() {}
  union {
    ImageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageRequestDefaultTypeInternal _ImageRequest_default_instance_;

inline constexpr ImageReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : processed_image_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ImageReply::ImageReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ImageReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageReplyDefaultTypeInternal() {}
  union {
    ImageReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageReplyDefaultTypeInternal _ImageReply_default_instance_;
}  // namespace imageprocessor
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_imageprocessor_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_imageprocessor_2eproto = nullptr;
const ::uint32_t
    TableStruct_imageprocessor_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::imageprocessor::ImageRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::imageprocessor::ImageRequest, _impl_.image_data_),
        PROTOBUF_FIELD_OFFSET(::imageprocessor::ImageRequest, _impl_.operation_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::imageprocessor::ImageReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::imageprocessor::ImageReply, _impl_.processed_image_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::imageprocessor::ImageRequest)},
        {10, -1, -1, sizeof(::imageprocessor::ImageReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::imageprocessor::_ImageRequest_default_instance_._instance,
    &::imageprocessor::_ImageReply_default_instance_._instance,
};
const char descriptor_table_protodef_imageprocessor_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024imageprocessor.proto\022\016imageprocessor\"5"
    "\n\014ImageRequest\022\022\n\nimage_data\030\001 \001(\014\022\021\n\top"
    "eration\030\002 \001(\t\"%\n\nImageReply\022\027\n\017processed"
    "_image\030\001 \001(\0142Z\n\016ImageProcessor\022H\n\014Proces"
    "sImage\022\034.imageprocessor.ImageRequest\032\032.i"
    "mageprocessor.ImageReplyb\006proto3"
};
static ::absl::once_flag descriptor_table_imageprocessor_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_imageprocessor_2eproto = {
    false,
    false,
    232,
    descriptor_table_protodef_imageprocessor_2eproto,
    "imageprocessor.proto",
    &descriptor_table_imageprocessor_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_imageprocessor_2eproto::offsets,
    file_level_enum_descriptors_imageprocessor_2eproto,
    file_level_service_descriptors_imageprocessor_2eproto,
};
namespace imageprocessor {
// ===================================================================

class ImageRequest::_Internal {
 public:
};

ImageRequest::ImageRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageprocessor.ImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE ImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::imageprocessor::ImageRequest& from_msg)
      : image_data_(arena, from.image_data_),
        operation_(arena, from.operation_),
        _cached_size_{0} {}

ImageRequest::ImageRequest(
    ::google::protobuf::Arena* arena,
    const ImageRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ImageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:imageprocessor.ImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE ImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : image_data_(arena),
        operation_(arena),
        _cached_size_{0} {}

inline void ImageRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ImageRequest::~ImageRequest() {
  // @@protoc_insertion_point(destructor:imageprocessor.ImageRequest)
  SharedDtor(*this);
}
inline void ImageRequest::SharedDtor(MessageLite& self) {
  ImageRequest& this_ = static_cast<ImageRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.image_data_.Destroy();
  this_._impl_.operation_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ImageRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ImageRequest(arena);
}
constexpr auto ImageRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ImageRequest),
                                            alignof(ImageRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ImageRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ImageRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ImageRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ImageRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ImageRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ImageRequest>(), &ImageRequest::ByteSizeLong,
            &ImageRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_._cached_size_),
        false,
    },
    &ImageRequest::kDescriptorMethods,
    &descriptor_table_imageprocessor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ImageRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 45, 2> ImageRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageprocessor::ImageRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string operation = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.operation_)}},
    // bytes image_data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.image_data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes image_data = 1;
    {PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.image_data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string operation = 2;
    {PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.operation_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\0\11\0\0\0\0\0"
    "imageprocessor.ImageRequest"
    "operation"
  }},
};

PROTOBUF_NOINLINE void ImageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:imageprocessor.ImageRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.image_data_.ClearToEmpty();
  _impl_.operation_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ImageRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ImageRequest& this_ = static_cast<const ImageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ImageRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ImageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:imageprocessor.ImageRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes image_data = 1;
          if (!this_._internal_image_data().empty()) {
            const std::string& _s = this_._internal_image_data();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // string operation = 2;
          if (!this_._internal_operation().empty()) {
            const std::string& _s = this_._internal_operation();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "imageprocessor.ImageRequest.operation");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:imageprocessor.ImageRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ImageRequest::ByteSizeLong(const MessageLite& base) {
          const ImageRequest& this_ = static_cast<const ImageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ImageRequest::ByteSizeLong() const {
          const ImageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:imageprocessor.ImageRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes image_data = 1;
            if (!this_._internal_image_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_image_data());
            }
            // string operation = 2;
            if (!this_._internal_operation().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_operation());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ImageRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ImageRequest*>(&to_msg);
  auto& from = static_cast<const ImageRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:imageprocessor.ImageRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_image_data().empty()) {
    _this->_internal_set_image_data(from._internal_image_data());
  }
  if (!from._internal_operation().empty()) {
    _this->_internal_set_operation(from._internal_operation());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageRequest::CopyFrom(const ImageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:imageprocessor.ImageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImageRequest::InternalSwap(ImageRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_data_, &other->_impl_.image_data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.operation_, &other->_impl_.operation_, arena);
}

::google::protobuf::Metadata ImageRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ImageReply::_Internal {
 public:
};

ImageReply::ImageReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:imageprocessor.ImageReply)
}
inline PROTOBUF_NDEBUG_INLINE ImageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::imageprocessor::ImageReply& from_msg)
      : processed_image_(arena, from.processed_image_),
        _cached_size_{0} {}

ImageReply::ImageReply(
    ::google::protobuf::Arena* arena,
    const ImageReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ImageReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:imageprocessor.ImageReply)
}
inline PROTOBUF_NDEBUG_INLINE ImageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : processed_image_(arena),
        _cached_size_{0} {}

inline void ImageReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ImageReply::~ImageReply() {
  // @@protoc_insertion_point(destructor:imageprocessor.ImageReply)
  SharedDtor(*this);
}
inline void ImageReply::SharedDtor(MessageLite& self) {
  ImageReply& this_ = static_cast<ImageReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.processed_image_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ImageReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ImageReply(arena);
}
constexpr auto ImageReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ImageReply),
                                            alignof(ImageReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ImageReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ImageReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ImageReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ImageReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ImageReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ImageReply>(), &ImageReply::ByteSizeLong,
            &ImageReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ImageReply, _impl_._cached_size_),
        false,
    },
    &ImageReply::kDescriptorMethods,
    &descriptor_table_imageprocessor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ImageReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ImageReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::imageprocessor::ImageReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes processed_image = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ImageReply, _impl_.processed_image_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes processed_image = 1;
    {PROTOBUF_FIELD_OFFSET(ImageReply, _impl_.processed_image_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ImageReply::Clear() {
// @@protoc_insertion_point(message_clear_start:imageprocessor.ImageReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.processed_image_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ImageReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ImageReply& this_ = static_cast<const ImageReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ImageReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ImageReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:imageprocessor.ImageReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes processed_image = 1;
          if (!this_._internal_processed_image().empty()) {
            const std::string& _s = this_._internal_processed_image();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:imageprocessor.ImageReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ImageReply::ByteSizeLong(const MessageLite& base) {
          const ImageReply& this_ = static_cast<const ImageReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ImageReply::ByteSizeLong() const {
          const ImageReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:imageprocessor.ImageReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bytes processed_image = 1;
            if (!this_._internal_processed_image().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_processed_image());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ImageReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ImageReply*>(&to_msg);
  auto& from = static_cast<const ImageReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:imageprocessor.ImageReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_processed_image().empty()) {
    _this->_internal_set_processed_image(from._internal_processed_image());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageReply::CopyFrom(const ImageReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:imageprocessor.ImageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImageReply::InternalSwap(ImageReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.processed_image_, &other->_impl_.processed_image_, arena);
}

::google::protobuf::Metadata ImageReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace imageprocessor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_imageprocessor_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
