// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: imageprocessor.proto

#include "imageprocessor.pb.h"
#include "imageprocessor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace imageprocessor {

static const char* ImageProcessor_method_names[] = {
  "/imageprocessor.ImageProcessor/ProcessImage",
};

std::unique_ptr< ImageProcessor::Stub> ImageProcessor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageProcessor::Stub> stub(new ImageProcessor::Stub(channel, options));
  return stub;
}

ImageProcessor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ProcessImage_(ImageProcessor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ImageProcessor::Stub::ProcessImage(::grpc::ClientContext* context, const ::imageprocessor::ImageRequest& request, ::imageprocessor::ImageReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::imageprocessor::ImageRequest, ::imageprocessor::ImageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessImage_, context, request, response);
}

void ImageProcessor::Stub::async::ProcessImage(::grpc::ClientContext* context, const ::imageprocessor::ImageRequest* request, ::imageprocessor::ImageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::imageprocessor::ImageRequest, ::imageprocessor::ImageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessImage_, context, request, response, std::move(f));
}

void ImageProcessor::Stub::async::ProcessImage(::grpc::ClientContext* context, const ::imageprocessor::ImageRequest* request, ::imageprocessor::ImageReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessImage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::imageprocessor::ImageReply>* ImageProcessor::Stub::PrepareAsyncProcessImageRaw(::grpc::ClientContext* context, const ::imageprocessor::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::imageprocessor::ImageReply, ::imageprocessor::ImageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessImage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::imageprocessor::ImageReply>* ImageProcessor::Stub::AsyncProcessImageRaw(::grpc::ClientContext* context, const ::imageprocessor::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessImageRaw(context, request, cq);
  result->StartCall();
  return result;
}

ImageProcessor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageProcessor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageProcessor::Service, ::imageprocessor::ImageRequest, ::imageprocessor::ImageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ImageProcessor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::imageprocessor::ImageRequest* req,
             ::imageprocessor::ImageReply* resp) {
               return service->ProcessImage(ctx, req, resp);
             }, this)));
}

ImageProcessor::Service::~Service() {
}

::grpc::Status ImageProcessor::Service::ProcessImage(::grpc::ServerContext* context, const ::imageprocessor::ImageRequest* request, ::imageprocessor::ImageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace imageprocessor

